### ISSUE TITLE
Question: how do I correctly include libint2.h in pure C code?

### ISSUE THREAD

**Issue by zc62** [evaleev/libint#105]
I am using release 2.4.2. While I am compiling a piece of pure C code that uses libint2, I got a compilation error:
```
In file included from /home/xxx/local/include/libint2/libint2_types.h(25),
                 from /home/xxx/local/include/libint2/util/generated/libint2_types.h(26),
                 from /home/xxx/local/include/libint2.h(35),
                 from /home/xxx/source/include/xxxxx.h(12),
                 from /home/xxx/source/xxxxxxxxxxxx.c(18):
/home/xxx/local/include/libint2/util/memory.h(24): catastrophic error: cannot open source file "cstdlib"
```
I found this `memory.h` is in pure C++. Did I do anything wrong? I think `libint2.h` is intended to be C-compatible?

**Comment by evaleev** [comment]
sorry, C got broken due to missing tests. This is resolved via 449621140fc3322d9a8e51581c2b3900cb66d4ad ... will make 2.5.0-beta.2 shortly
