### ISSUE TITLE
Add user defined libint2::Operator to calculate exchange correlation matrix

### ISSUE THREAD

**Issue by tgzhou98** [evaleev/libint#116]
I'm trying to implement a toy dft related program by using libint library. Since the `libint2::Operator` list in the [wiki](https://github.com/evaleev/libint/wiki/using-modern-CPlusPlus-API) page don't have `V_xc` like operator, I have to divide space to Lebedev-Laikov grids and do integration by myself.

So I wonder that is there any API can facilitate this process or a feature can be added?

**Comment by evaleev** [comment]
At the moment there are no plans to implement this since the current one-shell-set API is likely to be suboptimal + cooperation with other libraries is needed. There are other libraries that already do this, e.g. https://github.com/dgasmith/gau2grid from @dgasmith
