### ISSUE TITLE
include/libint2/diis.h

### ISSUE THREAD

**Issue by swillow** [evaleev/libint#117]
Please check the following line.
----
line number 250:
A.block(1, 1, rank-1, rank-1) = B_.block(nskip, nskip, rank-1, rank-1)*norm;
-->
A.block(1, 1, rank-1, rank-1) = B_.block(nskip, nskip, nvec-1, nvec-1)*norm;
----

**Comment by evaleev** [comment]
3rd and 4th args to block are block sizes, hence they must match on both sides. see https://eigen.tuxfamily.org/dox/group__TutorialBlockOperations.html

**Comment by swillow** [comment]
I did not check whether there is a difference between Eigen and armadillo
(in the definition of submatrix or block).

Thanks,

Soohaeng
