### ISSUE TITLE
Error for compile bagle with interface to libint

### ISSUE THREAD

**Issue by okunoyukihiro** [evaleev/libint#126]
Dear libint developers. 

I'm now tring to compile the bagle with interface  to libint. 

First we tried to make library of libint with the configure option 
configure --enable-eri=1 --enable-eri3=1 --enable-eri2=1 --with-max-am=6 --with-cartgauss-ordering=bagel --enable-contracted-ints --with-cxx-optflags=-O2 --with-cxx=g++ --prefix=・libint-master_gcc_7.1.0 CXXFLAGS=-I/Boost/boost_1_67_0/include LDFLAGS=-L/Boost/boost_1_67_0/lib

make all.

We could compiled libint2 library with no problem,.

Then, I tried to compile bagle with option 

./configure CXXFLAGS=-DNDEBUG -DLIBINT_INTERFACE -O2 -mcmodel=large --enable-mkl --with-boost=/Boost/boost_1_67_0 -with-mpi=intel --with-include=-I/libint/libint-master_gcc_7.1.0/include/libint2 -I/libint/libint-master_gcc_7.1.0/include -I/Boost/boost_1_67_0/include LDFLAGS=-Llibint/libint-master_gcc_7.1.0/lib -L/Boost/boost_1_67_0/lib -lint2 -lboost_regex

make 

The error with message  as follow has occured at the making library for bagle, 
/usr/bin/ld: /libint/libint-master_gcc_7.1.0/lib/libint2.a(libint2_init.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/home/okuno/libint/libint-master_gcc_7.1.0/lib/libint2.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status.

It seems error  is  originated from making the static library with libint2.a 

How should we treat the error ? Is it need to add some option to compile libint2.a ? 

If I can receive reply, I will be very happy. 

Sincerely, 

Yukihiro Okuno.

**Comment by evaleev** [comment]
Dear Dr. Okuno:

You may need to compile libint as a shared library by adding
--enable-shared --disable-static to the libint configure command. It is
best to remove the installed libint directory tree so that only a shared
library is present in the installation directory.

Please let me know if this fixes the problem.

Sincerely,

Edward Valeev.

**Comment by evaleev** [comment]
is this issue still relevant, @okunoyukihiro ?

**Comment by okunoyukihiro** [comment]
Dear Dr Valeev  

Sorry for may  late reply, and thank you for your reply.

I had tried to compile libinit2 with option 

 ../configure --enable-eri=1 --enable-eri3=1 --enable-eri2=1 --with-max-am=6\
 --with-cartgauss-ordering=bagel --enable-contracted-ints --enable-shared --dis\
able-static --with-cxx-optflags=-O2 --with-cxx=g++ --prefix=/home/okuno/libint/\
libint-master_gcc_7.1.0_shared CXXFLAGS=-I/home/okuno/Boost/boost_1_69_0_gcc/includ\
e -fPIC LDFLAGS=-L/home/okuno/Boost/boost_1_69_0_gcc/lib

and  also compiled Bagle with option 

./configure CXXFLAGS=-DNDEBUG -DLIBINT_INTERFACE -O2 -mcmodel=large -fPIC --enable-mkl --with-boost=/home/okuno/Boost/boos\
t_1_69_0_gcc -with-mpi=intel --with-include=-I/home/okuno/libint/libint-master_gcc_7.1.0/include/libint2 -I/home/okuno/libint/l\
ibint-master_gcc_7.1.0/include -I/home/okuno/Boost/boost_1_69_0_gcc/include LDFLAGS=-L/home/okuno/libint/libint-master_gcc_7.1.\
0/lib -L/home/okuno/Boost/boost_1_69_0_gcc/lib -lint2 -lboost_regex -lboost_iostreams --prefix=/home/okuno/Bagel/bin

-fPIC  option (intel compiler ) remove the error and I could compiled Bagel. 

However,  I run the bagle  with sample file. 

Bagel  benzene_svp_mp2.json 

Core dumped has occurred.  I'm now investigating the origin of the error. 

Sincerely, 

Yukihiro Okuno 

 
I'm now investigate the origin of  

.
