### ISSUE TITLE
GMP path setup

### ISSUE THREAD

**Issue by lqhenwunai** [evaleev/libint#129]
Hi,

I tried to compile libint-2.6 with the following configure arguments:
../../libint-2.6/configure --with-cxx=g++ --with-cxx-optflags=-O2 --enable-1body=2 --enable-eri=2 --enable-eri2=2 --enable-eri3=2 --with-max-am=6
(I want 2nd derivatives and support of angular momentum up to 6, not the 2nd derivatives of l=6)

The configure then complains that:
| #include <gmpxx.h>
configure:6716: result: no
configure:6716: checking for gmpxx.h
configure:6716: result: no
configure:6770: error: cannot link against GMP C++ library. Please get the latest GMP with support for C++. It can be obtained at gmplib.org .

Thus I installed gmp-6.1.2 with ./configure --prefix=/usr/local/include/gmp --enable-cxx, and re-compile. However unfortunately the same error occurs. 

while find /usr/local/ -name "libgmp*", it returns:
/usr/local/include/gmp/lib/libgmp.a
/usr/local/include/gmp/lib/libgmp.so.10.3.2
/usr/local/include/gmp/lib/libgmp.so
/usr/local/include/gmp/lib/libgmp.so.10
/usr/local/include/gmp/lib/libgmp.la
/usr/local/lib/libgmp.a
/usr/local/lib/libgmp.so.10.3.2
/usr/local/lib/libgmp.so
/usr/local/lib/libgmp.so.10
/usr/local/lib/libgmp.la

and when find /usr/local/ -name gmpxx.h, it returns:
/usr/local/include/gmp/include/gmpxx.h

I am not sure how to correctly setup the path of GMP for libint-2.6.

Many thanks for your help.

**Comment by evaleev** [comment]
try setting CPPFLAGS to '-I/usr/local/include' and LDFLAGS to '/usr/local/lib'.

You can specify maximum angular momenta for each derivative order, e.g. as done for Orca: '--enable-eri=2' '--enable-eri3=2' '--enable-eri2=2' '--with-max-am=7' '--with-opt-am=4' '--with-eri-max-am=7,4,3' '--with-eri-opt-am=4,3,2' '--disable-unrolling' '--enable-generic-code' '--enable-contracted-ints' '--with-cartgauss-ordering=orca' '--with-shell-set=orca' '--enable-eri3-pure-sh' '--enable-eri2-pure-sh'
