### ISSUE TITLE
cc-pvtz basis not matching basissetexchange.org

### ISSUE THREAD

**Issue by hongzhouye** [evaleev/libint#132]
The cc-pVTZ basis as defined in `lib/basis/cc-pvtz.g94` does not match those from the [https://www.basissetexchange.org/](url). For example, the basis for hydrogen in the above file is
```
H     0 
S   3   1.00
     33.8700000              0.0060680        
      5.0950000              0.0453080        
      1.1590000              0.2028220        
S   1   1.00
      0.3258000              1.0000000        
S   1   1.00
      0.1027000              1.0000000        
P   1   1.00
      1.4070000              1.0000000        
P   1   1.00
      0.3880000              1.0000000        
D   1   1.00
      1.0570000              1.0000000
****
```
while the one from the basissetexchange website is
```
H     0
S   5   1.00
      3.387000D+01           6.068000D-03
      5.095000D+00           4.530800D-02
      1.159000D+00           2.028220D-01
      3.258000D-01           5.039030D-01
      1.027000D-01           3.834210D-01
S   1   1.00
      3.258000D-01           1.000000D+00
S   1   1.00
      1.027000D-01           1.000000D+00
P   1   1.00
      1.407000D+00           1.000000D+00
P   1   1.00
      3.880000D-01           1.000000D+00
D   1   1.00
      1.057000D+00           1.0000000
****
```
The problem lies in the first 1s orbitals: 3s --> 1s vs 5s --> 1s. Similar problems exist for all other atoms (and shells with higher angular momenta).

**Comment by evaleev** [comment]
The difference is due to the use of standard correlation-consistent basis sets in BSE. Libint includes the versions with segmented contractions optimized. These are equivalent up to numerical roundoff (the optimized version's contraction is not unit normalized though ... Not an issue either.

**Comment by hongzhouye** [comment]
I see. Thanks, Professor Valeev!

Hongzhou Ye
Department of Chemistry, MIT
Cambridge, MA, 02139
