### ISSUE TITLE
no makefile generated in build/src/lib/libint/src

### ISSUE THREAD

**Issue by lyzxyn** [evaleev/libint#133]
Hi,
I used MSYS2 (http://www.msys2.org) under windows 7 to compile the libint 2.5.0 and got the following error:
generating code for OSVRRP1InBra_aB_l__0__d__1___TwoPRep_s__0__s__1___Ab__up_0 target=< l(0) d(1) | TwoPRep | s(0) s(1) > ^ { {0} }
generating code for OSVRRP1InBra_aB_l__0__p__1___TwoPRep_s__0__s__1___Ab__up_0 target=< l(0) p(1) | TwoPRep | s(0) s(1) > ^ { {0} }
generating code for OSVRRP0InBra_aB_l__0__s__1___TwoPRep_s__0__s__1___Ab__up_0 target=< l(0) s(1) | TwoPRep | s(0) s(1) > ^ { {0} }
Compilation finished. Goodbye.
echo "Last time library source was generated:\c" > source
date >> source
cd src; make TO_TOPDIR=../../.. TOPDIR=/e/Chemsoft/libint/build/src/lib/libint/../../.. SRCDIR=/e/Chemsoft/libint/libint-2.5.0/src/lib/libint
make[4]: Entering directory “/e/Chemsoft/libint/build/src/lib/libint/src”
make[4]: *** no destination and can not find makefile。 STOP。
make[4]: Entering directory“/e/Chemsoft/libint/build/src/lib/libint/src”
make[3]: *** [../../../src/lib/MakeRules:19：../../../lib/libint2.la] error 2
make[3]: Entering directory“/e/Chemsoft/libint/build/src/lib/libint”
make[2]: *** [/e/Chemsoft/libint/libint-2.5.0/src/lib/Makefile:11：default] error 1
make[2]: Entering directory“/e/Chemsoft/libint/build/src/lib”
make[1]: *** [/e/Chemsoft/libint/libint-2.5.0/src/Makefile:11：default] error 1
make[1]: Entering directory“/e/Chemsoft/libint/build/src”
make: *** [/e/Chemsoft/libint/libint-2.5.0/Makefile:15：default] error 1

My config log file is 
[config.log](https://github.com/evaleev/libint/files/3361776/config.log)

I have checked the directory of build/src/lib/libint/src and no Makefile is found in this directory.

Any help will be appreciated.

Youzhao Lan

**Comment by evaleev** [comment]
Unfortunately I don't have access to a Windows machine ... here are some pointers. Does `build/src/lib/libint/src` symbolic link exist? It should point to `build/src/lib/libint/tmp/libint` ... and Makefile should have been copied to it via the `$(LIBSRCDIR)/Makefile` rule in `build/src/lib/MakeRules` ... 
 
If still having issues I recommend you avoid compiling in the compiler tree. Instead, generate a library via `make export` and then build the generated library. The latest 2.6.0 beta has full support for CMake build of the exported library, so I recommend that as the most robust way to build.

**Comment by lyzxyn** [comment]
Great thanks for your help.  
I just know that MSYS2 system does not support the symbolic link. I manually copy the Makefile to the directroy of build\src\lib\libint\src. It works fine now.

Best regards
Youzhao Lan

**Comment by evaleev** [comment]
Good to know, thank you!

A workaround is to export a LIBINT library on a non-MSYS2 platform and then compile it on MSYS2.
