### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by ajaypanyala** [evaleev/libint#135]
Building `libint2.6.0-beta6` as follows on MacOS:
(Same issue with AppleClang and brew installed gcc)

cmake -DCMAKE_CXX_FLAGS_INIT="-march=native -Wno-unused-variable" -DCMAKE_BUILD_TYPE=Release -GNinja

ninja -j12

[4217/4217] Linking CXX static library libint2.a
FAILED: libint2.a 
: && /usr/local/Cellar/cmake/3.14.5/bin/cmake -E remove libint2.a && /usr/bin/ar qc libint2.a  @CMakeFiles/int2.rsp && /usr/bin/ranlib libint2.a && /usr/local/Cellar/cmake/3.14.5/bin/cmake -E touch libint2.a && :
ar: @CMakeFiles/int2.rsp: No such file or directory
ninja: build stopped: subcommand failed.

**Comment by evaleev** [comment]
directly related to [this](https://gitlab.kitware.com/cmake/cmake/issues/16731)
