### ISSUE TITLE
no CMakeLists.txt found

### ISSUE THREAD

**Issue by lyzxyn** [evaleev/libint#139]
Dear all,
I compiled the libint by cmake and followed the guide of https://github.com/evaleev/libint/wiki ,
but I got the following error when I run "cmake . -DCMAKE_INSTALL_PREFIX=/usr/local":
no CMakeLists.txt file found in src directory.
How to generate this file?
Any help I will appreciate.

Youzhao Lan

**Comment by evaleev** [comment]
Are you compiling a library or the compiler itself? Libint compiler can only be built via autotools, not cmake.

**Comment by lyzxyn** [comment]
Oh, sorry, I have misunderstood the guide.

Youzhao Lan
