### ISSUE TITLE
Cannot enable Fortran binding generation

### ISSUE THREAD

**Issue by slacalle** [evaleev/libint#140]
Require Fortran bindings (libint_f) for cp2k build. 

From the information here: https://github.com/evaleev/libint/wiki

I cannot do a cmake build and use "-DENABLE_FORTRAN" as there are is no CMakeLists.txt file.

The "--enable-fortran" is also not recognized in the 2.5.0 release.

Can someone please advice on how to enable Fortran bindings generation?

**Comment by pseewald** [comment]
There are two steps in building libint:
1) generating the source code using the libint compiler
2) compiling libint library
Maybe you downloaded the libint compiler but you try to compile libint library.

For use with CP2K, you should not try to use the libint compiler, but use one of the custom libraries generated for CP2K. You can find them [here](https://github.com/cp2k/libint-cp2k).

**Comment by evaleev** [comment]
@slacalle are you trying to do this in the compiler build tree? ... the compiler cannot be built using `cmake`, and using it to generate a library directly is verboten to non-experts. If you need to generate a custom library, export it using `make export`, then build that using the CMake according to https://github.com/evaleev/libint/wiki#configuring-and-building-libint-library-of-version-260-and-higher

**Comment by evaleev** [comment]
did this get resolved?

**Comment by slacalle** [comment]
Hi @evaleev ,
Yes, It did. I had to do the `make export` in order to build with cmake.

Thanks for the assist!

**Comment by zerothi** [comment]
Perhaps this could be clarified in the wiki a bit more?
I.e. I also did the mistake here ;)
