### ISSUE TITLE
autoreconf not working

### ISSUE THREAD

**Issue by mbanck** [evaleev/libint#146]
I know `autogen.sh` is provided, but I think it would be nice if plain `autoreconf` worked. Right now it doesn't because some/all of the `AC_DEFINE_UNQUOTED` in `configure.ac` do not have descriptions; they are present in `include/libint2/config.h.in` for the most part though.

**Comment by evaleev** [comment]
since autotools harness will be replaced by cmake, and the limited headcount, will not fix this
