### ISSUE TITLE
c++ interface questions

### ISSUE THREAD

**Issue by loriab** [evaleev/libint#152]
Hi, we're gathered to work on Libint2 and Psi4 again and have some questions.
* _With_ `--enable-eri3-pure-sh` one can only use sph aux basis sets. `_Without_ that flag, can one only use cart or can one use sph or cart?
* The C++11 interface isn't using vectorization now. Is that planned for the future?
* Is it essential to use the templated `compute2` fns if you want to pass `ShellPair` objects in?

Thanks for any guidance.

**Comment by evaleev** [comment]
> * _With_ `--enable-eri3-pure-sh` one can only use sph aux basis sets. `_Without_ that flag, can one only use cart or can one use sph or cart?

can do either without.

> * The C++11 interface isn't using vectorization now. Is that planned for the future?

"planned" in a loose sense. It would have to be Libint v3.

> * Is it essential to use the templated `compute2` fns if you want to pass `ShellPair` objects in?

It's the only place where shell-pair data can be fed at the moment, so yes. The amount of metaprogramming sans c++17 in the variadic `compute()` method would be difficult to justify (assuming for the moment that the usual c++ rules governing where variadic param pack do not apply ... I'm not even sure where the defaultable `ShellPair` args would go). What's the use case where the templated method is not convenient?

**Comment by loriab** [comment]
Thanks for the guidance -- I think Andy got passed the ShellPair/compute2 difficulty.
