### ISSUE TITLE
examples to call libint 

### ISSUE THREAD

**Issue by lqhenwunai** [evaleev/libint#155]
Dear Prof. Valeev, 

If at your convenience, can you give some simple and straightforward examples to call libint for molecular integral calculations?

Perhaps one example for kinetic/overlap integrals and one example for two-electron integrals.

Many thanks for your time.

**Comment by evaleev** [comment]
do you mean more than the examples provided [here](https://github.com/evaleev/libint/wiki/using-modern-CPlusPlus-API)? What do you have in mind: something as simple as create a basis, compute all integrals of a particular type? Or do you want to be able to control how work in shell loops is partitioned?

**Comment by lqhenwunai** [comment]
I think that is all I need. Many thanks!
