### ISSUE TITLE
problems about BasisSet object

### ISSUE THREAD

**Issue by lqhenwunai** [evaleev/libint#163]
Dear all,

I am trying to use libint to interface with our own codes. For test purpose, in the hartree-fock.cc example file, I wrote:

libint2::BasisSet obs("cc-pVDZ",atoms);

after the vector<Atom> atoms reading geometries. Namely:
{

    /*** =========================== ***/
    /*** initialize molecule         ***/
    /*** =========================== ***/

    // read geometry from a file; by default read from h2o.xyz, else take filename (.xyz) from the command line
    const auto filename = (argc > 1) ? argv[1] : "h2o.xyz";
    std::vector<Atom> atoms = read_geometry(filename);

     //here I try to create BasisSet object, but failed.
    libint2::BasisSet obs("cc-pVDZ",atoms);

}
\---------------------------------------

However, the compilation says:
hartree-fock.cc:86:42: error: no matching function for call to ‘libint2::BasisSet::BasisSet(const char [8], std::vector<Atom>&)’
     libint2::BasisSet obs("cc-pVDZ",atoms);

I am using libint-2.6. 

Is there something changed in libint-2.6 but not updated in libint-WIKI?
And what is the basis set format for built-in basis sets? If I need to read in a non-standard basis set, how do I create corresponding BasisSet object?

Many thanks for your help.

best

**Comment by evaleev** [comment]
@lqhenwunai  please post your entire code, compile command + full output, and other details (at least the compiler version)

**Comment by lqhenwunai** [comment]
@evaleev 
The input file "hartree-fock.cc" is uploaded as the .txt file. I simply add
libint2::BasisSet obs("cc-pVDZ",atoms);
at line 86.

[hartree-fock.txt](https://github.com/evaleev/libint/files/4260039/hartree-fock.txt)

The compile command is simply "make". The related compiler versions are 
GNU Make 4.1
gcc version 7.4.0

The output is as follows:
luq@desktop:~/projects/libint-2.6/libint-master/tests/hartree-fock$ make
g++ -O2 -DNDEBUG  -DHAVE_CONFIG_H  -I../../src/bin -I../../include -I/home/luq/projects/libint-2.6/libint-master/tests/hartree-fock/../../include -I/home/luq/projects/libint-2.6/libint-master/tests/hartree-fock/../../src/bin  -I/usr/include -I../../include -I../../include/libint2 -I/home/luq/projects/libint-2.6/libint-master/tests/hartree-fock/../../src/lib/libint -DSRCDATADIR=\"/home/luq/projects/libint-2.6/libint-master/tests/hartree-fock/../../lib/basis\" -I/home/luq/projects/libint-2.6/libint-master/tests/hartree-fock/../../src/bin/libint -I../../src/bin/libint  -c -o hartree-fock.o hartree-fock.cc
hartree-fock.cc: In function ‘int main(int, char**)’:
hartree-fock.cc:86:42: error: no matching function for call to ‘libint2::BasisSet::BasisSet(const char [8], std::vector<Atom>&)’
     libint2::BasisSet obs("cc-pVDZ",atoms);
                                          ^
In file included from ../../include/libint2/cxxapi.h:92:0,
                 from ../../include/libint2.hpp:24,
                 from hartree-fock.cc:35:
../../include/libint2/basis.h:145:7: note: candidate: libint2::BasisSet::BasisSet(const std::vector<libint2::Atom>&, const std::vector<std::vector<libint2::Shell> >&, std::__cxx11::string, bool)
       BasisSet(const std::vector<Atom>& atoms,
       ^~~~~~~~
../../include/libint2/basis.h:145:7: note:   no known conversion for argument 1 from ‘const char [8]’ to ‘const std::vector<libint2::Atom>&’
../../include/libint2/basis.h:85:7: note: candidate: libint2::BasisSet::BasisSet(std::__cxx11::string, const std::vector<libint2::Atom>&, bool)
       BasisSet(std::string name,
       ^~~~~~~~
../../include/libint2/basis.h:85:7: note:   no known conversion for argument 2 from ‘std::vector<Atom>’ to ‘const std::vector<libint2::Atom>&’
../../include/libint2/basis.h:52:7: note: candidate: libint2::BasisSet::BasisSet(libint2::BasisSet&&)
       BasisSet(BasisSet&& other) :
       ^~~~~~~~
../../include/libint2/basis.h:52:7: note:   candidate expects 1 argument, 2 provided
../../include/libint2/basis.h:51:7: note: candidate: libint2::BasisSet::BasisSet(const libint2::BasisSet&)
       BasisSet(const BasisSet&) = default;
       ^~~~~~~~
../../include/libint2/basis.h:51:7: note:   candidate expects 1 argument, 2 provided
../../include/libint2/basis.h:50:7: note: candidate: libint2::BasisSet::BasisSet()
       BasisSet() : name_(""), nbf_(-1), max_nprim_(0), max_l_(-1) {}
       ^~~~~~~~
../../include/libint2/basis.h:50:7: note:   candidate expects 0 arguments, 2 provided
<builtin>: recipe for target 'hartree-fock.o' failed
make: *** [hartree-fock.o] Error 1

**Comment by evaleev** [comment]
on line 46 you defined struct `Atom` which is then used to define the type of variable `atoms`. Constructor for BasisSet expects a vector of `libint2::Atom`s, not a vector of your `Atom`s.

You are clearly trying to adjust hartree-fock.cc example to use BasisSet ... replace the definition of `Atom` with `using Atom = libint2::Atom` and it should compile. Replace `shells` with `obs` and it should at least get to the guess step. You will need to borrow more code from `hartree-fock++.cc` to make it do what you want.
