### ISSUE TITLE
Unable to build tests using tests/makefile

### ISSUE THREAD

**Issue by pmott91** [evaleev/libint#174]
I am trying to build the test programs that are in the tests subfolder of Libint. I am trying to run "make" using the Makefile in tests. It returns the following error:

/bin/sh   ../libtool --quiet --mode=link --tag=CXX      /sw/summit/gcc/6.4.0/bin/g++ -std=c++11    -L../lib -lint2 -lm   -o eri/test eri/test.o
/usr/bin/ld: cannot find -lint2
collect2: error: ld returned 1 exit status
make: *** [eri/test] Error 1

It appears to be trying to find a library file called lint2, but can't. I'm not sure where this file is supposed to be but I did some recursive searching and can't seem to find it anywhere. I'm trying to figure out when this file is supposed to be made so that I can figure out where the build process went wrong.

**Comment by evaleev** [comment]
all tests should be built and run via `make check` (`check` is the standard testing target of [GNU Conding Conventions](https://www.gnu.org/prep/standards/html_node/Standard-Targets.html#Standard-Targets)).

`-lint2` refers to `libint2.a` or `libint2.so` or `libint2.dylib`, etc.
