### ISSUE TITLE
Question regarding libint static init / cleanup

### ISSUE THREAD

**Issue by pseewald** [evaleev/libint#182]
Is it allowed to call `libint2_static_init` & `libint2_static_cleanup` more than once in a nested way? In our code (CP2K) we initialize libint by different methods that rely on libint (thus libint may be initialized more than once). According to the libint manual init/cleanup should be called once per program, so should we initialize libint always at the beginning of CP2K?

**Comment by evaleev** [comment]
@pseewald as of now it is fine to call this pair multiple times ... in the future it _may_ change (hence the request to call them once) but it is unlikely to.
