### ISSUE TITLE
CMake build documented, but completely broken

### ISSUE THREAD

**Issue by mboisson** [evaleev/libint#184]
Hi,
I'm trying to get the fortran bindings, which won't work with configure, and I discovered that 2.6.0 introduces cmake (according to the documentation here https://github.com/evaleev/libint/wiki#compiling-libint-library ), yet, this is completely broken since there is no CMakeLists.txt. 

```
[mboisson@build-node libint-2.6.0]$ cmake .
CMake Error: The source directory "/tmp/mboisson/avx2/Libint/2.6.0/GCC-9.3.0/libint-2.6.0" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI
```

**Comment by evaleev** [comment]
cmake build is only available right now for the generated library, not the compiler.

#205 will add the ability to use cmake for the entire libint project (compiler+library), but that won't appear until the end of the year.
