### ISSUE TITLE
Composite shells support.

### ISSUE THREAD

**Issue by JensWehner** [evaleev/libint#189]
Hello,

I could not find any documentation on the issue and the intricacies of the source code are beyond me. I saw that `libint::Shell` supports contractions with different angular momenta. So it seems to support `SP` shells. Does it internally split those shells up into pure `L` shells or is there a performance benefit of using combined shells in libint? If supporting combined shells is useful, does libint also allow for `SD`  or `PF` shells, i.e with a non-contiguous range of L. Can I make a `SPDF` shell?

Thanks for the great library.

**Comment by evaleev** [comment]
Dear @JensWehner : unfortunately the Engine does not yet support generally-contracted shells, e.g. see https://github.com/evaleev/libint/blob/master/include/libint2/engine.impl.h#L175 . For SP shells it should be possible to actually generate optimized code, but again lack of time and low priority keeps pushing this into the future ...

**Comment by evaleev** [comment]
Also: @JensWehner Shells are indeed completely general, so yes, a shell can be created with 1 `P` contraction and 1 `F` contraction, i.e. the `PF` shell. But Engine cannot use such Shells yet.

**Comment by JensWehner** [comment]
Thanks that makes the implementation easier.
