### ISSUE TITLE
Consider adding libint2 to zenodo for ease of citation

### ISSUE THREAD

**Issue by alejandrogallo** [evaleev/libint#197]
I'm citing libint2 and I'd like to have a `doi` for the project.
Please consider using the [zenodo](https://zenodo.org/)
project to automatically get a doi for every version.

An example of a software project would be for
[papis](https://github.com/papis/papis) at https://doi.org/10.5281/zenodo.3781278

**Comment by evaleev** [comment]
@alejandrogallo all Libint releases already to have zenodo DOIs, e.g. https://github.com/evaleev/libint/releases/tag/v2.7.0-beta.6
