### ISSUE TITLE
Libint2 Engine gives incorrect two-electron integral derivatives

### ISSUE THREAD

**Issue by adabbott** [evaleev/libint#198]
Thanks for writing and maintaining this awesome library!

I have recently cloned this repository, configured libint with options `--enable-eri=4` and `--with-max-am=2`, and have successfully compiled it with all tests passing. However, when using the C++11 API, I have found that the first derivatives of ERI's (`Engine` with `Operator::coulomb` and `deriv_order` set to 1) appears to compute some values that are incorrect, and others that are off by a factor of 2 when compared to Psi4, which I believe uses an older version of libint.

Below is the simplest minimal reproducible example I could come up with which demonstrates these errors. I have also included a python script which calls Psi4's ERI nuclear derivatives. Note that the geometry and basis sets need to match. 

```c++
#include <libint2.hpp>
#include <stdlib.h>

int main(int argc, char* argv[]) {
  using namespace libint2;
  using namespace std;
  libint2::initialize();
  // NOTE: Create h2.xyz to match psi4, change this path as needed
  string xyzfilename = "/home/adabbott/h2.xyz";
  ifstream input_file(xyzfilename);
  vector<Atom> atoms = read_dotxyz(input_file);
  BasisSet obs("sto-3g", atoms);
  int nbf = obs.nbf();
  int deriv_order = 1;
  Engine eri_engine(Operator::coulomb,obs.max_nprim(),obs.max_l(),deriv_order);
  const auto& buf_vec = eri_engine.results(); // will point to computed shell sets

  for(auto s1=0; s1!=obs.size(); ++s1) {
      auto n1 = obs[s1].size();    // number of basis functions in shell 1
      for(auto s2=0; s2!=obs.size(); ++s2) {
          auto n2 = obs[s2].size();    // number of basis functions in shell 2
          for(auto s3=0; s3!=obs.size(); ++s3) {
              auto n3 = obs[s3].size();    // number of basis functions in shell 3
              for(auto s4=0; s4!=obs.size(); ++s4) {
                  auto n4 = obs[s4].size();    // number of basis functions in shell 4
                  eri_engine.compute(obs[s1], obs[s2], obs[s3], obs[s4]);
                  // Print all of this shell quartet's first derivatives 
                  for(auto i=0; i<12; ++i){
                      for (auto j=0; j<(n1*n2*n3*n4); j++){
                          printf("%lf \n", buf_vec[i][j]);
                      }
                  }
              }
          }
      }
  }
  libint2::finalize();
  return 0;
}

// Compile with:
// g++ test.cc -o test -I/path/to/eigen3 -I/path/to/libint-2.x.x/include/libint2 -I/path/to/libint-2.x.x/include -L/path/to/libint2.a -lint2

```

```python
import psi4
import numpy as np

molecule = psi4.geometry("""
                         0 1
                         H  0.0  0.0  0.8
                         H  0.0  0.0 -0.8
                         units ang 
                         """)

basis_set = psi4.core.BasisSet.build(molecule, 'BASIS', "sto-3g", puream=0)
mints = psi4.core.MintsHelper(basis_set)

x1, y1, z1 = mints.ao_tei_deriv1(0)
x2, y2, z2 = mints.ao_tei_deriv1(1)
print(np.asarray(z1))
```

When running the above two examples, the following nonzero results (+/-) are returned from each code:
| Libint2      |  Psi4 | Difference |
| ----------- | ----------- | -------|
| 0.107214  | 0.107214    | correct |
| 0.022867   |  0.0457349 | *2  |
|0.049697 |  0.099394 |*2  |
| 0.079429 |  ???  | No match|
| 0.013892  | ??? |   No match |

I get identical results when configuring libint differently, e.g. with `--enable-eri=1` and `--with-max-am=1`.
@evaleev  Am I doing something wrong here? If this is indeed a bug, is there a simple workaround?

**Comment by adabbott** [comment]
Update: The Libint derivatives are correct, just different than what I expected. I did not realize the derivatives returned were respect to strictly shell center components, without considering that multiple shell centers are one and the same with regard to cartesian coordinates of the molecule. This is clear now.  A light suggestion: perhaps the wording of the [wiki](https://github.com/evaleev/libint/wiki/using-modern-CPlusPlus-API#geometric-derivatives) could be more precise, rather than saying "geometric derivatives" specifically say "shell center derivatives", and point out in a bullet point that these are not the same as, but may be used to derive,  _nuclear derivatives_ of the integrals.

The discrepancy with Psi4 is resolved if one sums the appropriate shell center derivatives to acquire the nuclear derivative.

**Comment by evaleev** [comment]
@adabbott thanks for the suggestion. I did not consider potential ambiguity here since Libint does not know anything about molecules. I.e. `Shell` do not sit on nuclei, they have has 3 origin coordinates that are not necessarily constrained to be identical to any other `Shell`'s origin. (n.b. Derivatives with respect to a particular center are sometimes useful).

`mints` is a higher-level abstraction, hence the difference in semantics.
