### ISSUE TITLE
Basis set format is not Gaussian'94

### ISSUE THREAD

**Issue by susilehtola** [evaleev/libint#206]
It appears the basis set format expected by libint2 is not Gaussian'94: libint should not expect the basis set to start with `****`. As a result, libint2 ignores the first element in basis sets given in Gaussian'94 format.

See also https://gitlab.com/eT-program/eT/-/issues/527

**Comment by evaleev** [comment]
@susilehtola new basis set exchange must have changed this ... I took most files from the old exchange at EMSL.

OK, thanks, will fix.
