### ISSUE TITLE
Incorrect cmake libint >=2.6.0 library build instructions

### ISSUE THREAD

**Issue by zachcran** [evaleev/libint#209]
I tried building the libint v2.6.0 pre-generated library ("lmax=6 library (standard ints only)") following the instructions in the Wiki at <https://github.com/evaleev/libint/wiki#configuring-and-building-libint-library-version-260-and-higher>, but ran into an issue while compiling with cmake.

When I ran the command on step 3 of compilation `cmake . -DCMAKE_INSTALL_PREFIX=[installation prefix] -DCMAKE_CXX_COMPILER=[C++ compiler] CXXFLAGS=[C++ compiler flags]` (filling in my information), I get the error:

```
The source directory "/path/to/libint2/libint-2.6.0/CXXFLAGS=-O3" does not exist.
``` 

I think `CXXFLAGS` needs to be replaced with `-DCMAKE_CXX_FLAGS`. That fixed it for me at least!

**Comment by evaleev** [comment]
@zachcran thanks, fixed
