### ISSUE TITLE
C++ compiler cannot create executables 

### ISSUE THREAD

**Issue by FreemanTheMaverick** [evaleev/libint#213]
My laptop is already equipped with clang++ and g++, but on configuring libint, it shows that
```
checking for clang++... clang++
checking whether the C++ compiler works... no
configure: error: in `/home/freeman/LibintCompiler':
configure: error: C++ compiler cannot create executables
```
I wonder why the C++ compiler does not work and how I can fix it. Many thanks.
Here is the log file.
[config.log](https://github.com/evaleev/libint/files/6921076/config.log)

**Comment by e-kwsm** [comment]
```
     7      $ ../libint/configure --enable-eri=2 --enable-eri3=2 --enable-eri2=2 CPPFLAGS=-I/usr/local/include LDFLAGS=/usr/local/lib CC=g++
```

- `LDFLAGS=/usr/local/lib` should be `LDFLAGS=-L/usr/local/lib`
- `CC=g++` should be `CXX=g++` or `CC=gcc`

**Comment by evaleev** [comment]
@FreemanTheMaverick , did @e-kwsm 's suggestions work?

**Comment by FreemanTheMaverick** [comment]
Thanks for the suggestions. But I've found that I don't really need to compile libint from scratch, so I just download a precompiled library. I appreciate your help anyway.
