### ISSUE TITLE
Is there any way to get the principal quantum number of a shell?

### ISSUE THREAD

**Issue by FreemanTheMaverick** [evaleev/libint#238]
Hi. Is there any way to get the principal quantum number of a shell? For example, the "1" in "1s" and the "2" in "2p". I looked it up in the source code but all I found is the way to get the angular quantum number.

**Comment by evaleev** [comment]
the concept of "principal" quantum number is not generally applicable, hence this is not possible. For ANO basis sets it may be applicable, but it's up to you to deduce the principal quantum number (1st orbital of any given angular momentum `l` has `n=l+1`, second -- `n=l+2`, etc.
