### ISSUE TITLE
Libint basis install

### ISSUE THREAD

**Issue by calewis** [evaleev/libint#27]
I am trying to install compile and install libint using commit b89d440e7b8e3aa1b63531dc117667ec14e752d5, after pulling I ran the following commands 

aclocal -Ilib/autoconf
autoconf 
cd build_dir
reconfigure 

make install 

I then get the following error at the very end of the install process 

/usr/bin/install -c -m 0644 ./lib/basis/*
/libint/install/dir/share/libint/2.1.0-beta/basis
install: ./lib/basis/*: No such file or directory make: ***
[install_data] Error 71

I looked at the MakeRules.export line 23 and it seems like it should call $SCRDIR/lib/basis/* but for some reason it is looking for the basis set files in the build dir and they are not there.

**Comment by calewis** [comment]
I compiled my code which links against libint and get the following error when I try to run. 

terminating with uncaught exception of type std::runtime_error: BasisSet::read_g94_basis_library(): could not open "/path/to/install/dirs/libint_clang/share/libint/2.1.0-beta/basis/sto-3g.g94"

So I think everything is working except for the installation of the actual basisset files.

**Comment by evaleev** [comment]
Did you run make install? It's the only easy to make sure the files get
installed. Alternatively you can use -DDATADIR or LIBINT_DATA_DIR

**Comment by calewis** [comment]
The output is the error at the end of make install 

make install 
....
/usr/bin/install -c -m 0644 ./lib/basis/*
/libint/install/dir/share/libint/2.1.0-beta/basis
install: ./lib/basis/: No such file or directory make: **
[install_data] Error 71
