### ISSUE TITLE
need to clang-format

### ISSUE THREAD

**Issue by evaleev** [evaleev/libint#294]
everything-at-once, like libc++: https://discourse.llvm.org/t/rfc-clang-formatting-all-of-libc-once-and-for-all/75198

GH can ignore formatting changes in its blame views: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Comment by loriab** [comment]
Related is bumping the year in each file's license header.

**Comment by evaleev** [comment]
> Related is bumping the year in each file's license header.

thanks for the reminder!

2.8.0 is dropping soon.

**Comment by evaleev** [comment]
fixed via https://github.com/evaleev/libint/pull/297
