### ISSUE TITLE
2.8.0 release

### ISSUE THREAD

**Issue by evaleev** [evaleev/libint#298]
this is to track issues with the just-released 2.8.0.

cc: @loriab

**Comment by loriab** [comment]
So far all's well. My toy conda builds all check out, and the production unix ones are building now.

Only thing I've noticed is that https://github.com/evaleev/libint/blob/master/export/cmake/CMakeLists.txt.export#L220 should be set back to TRUE. According to the boxed note in https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html#unity-build, it should be left under user control. But given it can speed up builds by 4x, I'm for imposing it on.

**Comment by loriab** [comment]
Also seem to have lost the definition of `ncoords`  here https://github.com/evaleev/libint/blob/master/tests/hartree-fock/hartree-fock%2B%2B.cc#L692 as `const auto ncoords = 3 * atoms.size();` . That only shows up for non-toy configurations.

**Comment by evaleev** [comment]
> Only thing I've noticed is that https://github.com/evaleev/libint/blob/master/export/cmake/CMakeLists.txt.export#L220 should be set back to TRUE. According to the boxed note in https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html#unity-build, it should be left under user control. But given it can speed up builds by 4x, I'm for imposing it on.

ouch, indeed, this looks like an accidental regression. Thanks, will fix

**Comment by JonathonMisiewicz** [comment]
> > Only thing I've noticed is that https://github.com/evaleev/libint/blob/master/export/cmake/CMakeLists.txt.export#L220 should be set back to TRUE. According to the boxed note in https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html#unity-build, it should be left under user control. But given it can speed up builds by 4x, I'm for imposing it on.
> 
> ouch, indeed, this looks like an accidental regression. Thanks, will fix

That's right, that get changed but didn't get restored when we were trying to get σ working on Windows.

**Comment by evaleev** [comment]
> Also seem to have lost the definition of `ncoords` here https://github.com/evaleev/libint/blob/master/tests/hartree-fock/hartree-fock%2B%2B.cc#L692 as `const auto ncoords = 3 * atoms.size();` . That only shows up for non-toy configurations.

ouch, fixed.

Progressing to 2.8.1 ...

**Comment by loriab** [comment]
All OS packages (linux, mac-intel, mac-silicon, windows) built cleanly at conda-forge. L, M, W conda packages were clean for partial Psi4 testing. Psi4 full tests with L package was clean. In summary, no further issues found for v2.8.0. I'll generate a high AM pkg overnight.

**Comment by JonathonMisiewicz** [comment]
My attempts to compile MPQC with 2.8.0 failed with include errors. Need #302 merged in to fix them.

**Comment by loriab** [comment]
Continuing this issue for the v2.8.1 release:

- [x] no problem with any of the builds so far. the usual production ones are now up on conda-forge https://anaconda.org/conda-forge/libint/files
- [ ] in case it gets buried in a closed issue, SOVERSION isn't entirely cleared up: https://github.com/evaleev/libint/pull/231#issuecomment-1863446271
