### ISSUE TITLE
it straight up doesn't work

### ISSUE THREAD

**Issue by 33MarGomez** [evaleev/libint#303]
!pip install -q condacolab
import condacolab
condacolab.install()

%%capture
!conda config --add channels http://conda.anaconda.org/psi4
!mamba install psi4 resp -c conda-forge/label/libint_dev -c conda-forge
!mamba install nglview ase -c conda-forge

from google.colab import output
output.enable_custom_widget_manager()

import psi4

returns: ModuleNotFoundError: No module named 'psi4'

**Comment by JonathonMisiewicz** [comment]
Why are you posting this as an issue to libint, rather than Psi4?

**Comment by loriab** [comment]
It's been reposted over at psi4.
