### ISSUE TITLE
Copy operator for OneBodyEngine false assert

### ISSUE THREAD

**Issue by wavefunction91** [evaleev/libint#32]
Attempt to copy OneBodyEngine fails on assert

...include/libint2/engine.h:334: void libint2::OneBodyEngine::initialize(): Assertion `false' failed.

Code snippet:
for(auto i = 1; i < nThreads; i++) engines[i] = engines[0];

Code that runs serially (i.e. nThreads.eq.1) throws no errors, only when I try to copy the configured OneBodyEngine (engines[0]).

**Comment by evaleev** [comment]
Fixed in 710169f
