### ISSUE TITLE
erf-attenuated nuclear integrals

### ISSUE THREAD

**Issue by philippwo** [evaleev/libint#323]
Dear All,
when using libint2 to calculate erf-attenuated nuclear-attraction integrals, the operator is defined as:
 \- \sum Z_I  erf(|r-R_I|)/|r-R_I|
 which takes into account the position (R_I) and the charge (Z_I) of the nucleus. If I wanted to transfer these integrals to non-nuclear charges (e. g. in PCM solvation models), the 'width' (Zeta_I) of the nucleus would also enter the operator as in:
\- \sum Z_I  erf(**Zeta_I** *|r-R_I|)/|r-R_I|
(example for this operator can be found in eq. 6 in 10.1021/acs.jctc.5b00370)

As far as I can see, that factor has a non-trivial effect, since it is within the error-function. 
Is this operator available in libint?
Best regards,
Philipp

**Comment by JonathonMisiewicz** [comment]
Yes. See example usage in the sample code [here](https://github.com/evaleev/libint/issues/242), where omega is set as the first parameter in the `params` tuple. You **must** use Libint 2.8.0 or newer for this, as #279 fixed a bug in these particular integrals.

**Comment by philippwo** [comment]
Thanks a lot for your help and the fast reply!
