### ISSUE TITLE
Can't use Boost build using CMake (aka modularized Boost)

### ISSUE THREAD

**Issue by evaleev** [evaleev/libint#332]
Modularized build of Boost is unofficial (https://github.com/boostorg/cmake/) yet usable and is currently being deployed into the VG stack (https://github.com/ValeevGroup/kit-cmake/pull/6). Unfortunately, modularized Boost lacks `Boost::boost` target, and alias targets cannot be used for [check_cxx_source_compiles](https://cmake.org/cmake/help/latest/module/CheckCXXSourceCompiles.html). Need to update code around https://github.com/evaleev/libint/blob/master/export/cmake/CMakeLists.txt.export#L131 to support this "corner" case

**Comment by loriab** [comment]
I'm not familiar with a modularized boost build. But if `headers` is indeed one of its components https://github.com/ValeevGroup/kit-cmake/pull/6/files#diff-0536d37aa9b13d9851f873d22bd563de764b0951903d0e598c11f0fe44e13527R100 , I think `Boost::boost` could be swapped out by `Boost::headers` now that minimum CMake is past 3.15.
