### ISSUE TITLE
Undefined reference to init and cleanup of emultipole(1,2)

### ISSUE THREAD

**Issue by wavefunction91** [evaleev/libint#34]
This problem only manifests without the -fpermissive flag (mysteriously slips by with -fpermissive). The following functions are said to have an undefined reference

libint2_cleanup_2emultipole
libint2_cleanup_1emultipole
libint2_init_1emultipole
libint2_init_2emultipole

**Comment by wavefunction91** [comment]
Fixed at the very latest in 2d94d006866d

**Comment by evaleev** [comment]
Thanks. Will close.
