### ISSUE TITLE
Couldn't clone libint repo on Windows

### ISSUE THREAD

**Issue by MehdiChinoune** [evaleev/libint#343]
Some files have `*` in their names, which is forbidden on Windows.
Because of that cloning libint repo fails on Windows.

Please consider rename those files and replace `*` by somthing acceptable by Windows.
Those files are:
- lib/basis/6-311**.g94
- lib/basis/6-31g**.g94
- lib/basis/6-31g*.g94

They are already symlinked (which is not natively supported on Windows) to files with `s` instead of `*`.

**Comment by loriab** [comment]
Yes, this is known. Brief orientation is that the libint _repo_ has source code that one compiles into an executable, the libint _generator_. The _generator_ is executed and writes files that are libint _library source_ (often libint _tarball_). One compiles the _library source_ to produce the libint _library_.

A few years ago, I had switched the `*` to `s`, adapted the generator build files for Windows (very minor changes), and got the tarball generated on Windwos. Trouble was the generated tarball was different from that produced by Linux/Mac and the resulting library didn't run correctly. A more common procedure for dealing with libint is to generate your tarball once on Linux or Mac (or use the tarball included with the release) and then compile it on Windows or any other platform. That's what the conda packages do.

So the clone problem stops you from further headaches :-) Certainly my experience was several years ago and there could be fixes, but with the generator run taking longer than the library build, Windows compatibility of the generator wasn't worth it for my use case (QC package on L/M/W).
