### ISSUE TITLE
Multiple definitions of OneBodyEngine default_params

### ISSUE THREAD

**Issue by wavefunction91** [evaleev/libint#35]
As of 8d4751a011cdf8f72fcbcc62556b8aba2cee03c1
Multiple definitions of several parameters upon link:

`libint2::OneBodyEngine::operator_traits<(libint2::OneBodyEngine::operator_type)2>::default_params'
`libint2::OneBodyEngine::operator_traits<(libint2::OneBodyEngine::operator_type)3>::default_params'
`libint2::OneBodyEngine::operator_traits<(libint2::OneBodyEngine::operator_type)4>::default_params'

**Comment by evaleev** [comment]
should be fixed in 9f2f1046d0c8129060cea7f4763bd9e4a61b287b
