### ISSUE TITLE
Make Export Failure

### ISSUE THREAD

**Issue by wavefunction91** [evaleev/libint#41]
As of fbcbb46af54, I obtain the followng error when attempting to export the Libint build

$ make export
...
/home/dbwy/git_repo/libint/build_gcc_libint/export/../config.status --config > ../libint-2.1.0-beta2/compiler.config
config.status: error: unrecognized option: --config
Try `/home/dbwy/git_repo/libint/build_gcc_libint/export/../config.status --help' for more information.

The compilation completes successfully. I configured with the following
$HOME/git_repo/libint/configure \
--enable-eri=1 \
--with-max-am=7 \
--with-opt-am=4 \
--disable-unrolling \
--enable-generic-code \
--enable-contracted-ints \
--with-incdirs=-I/usr/include/eigen3 \
--with-cxx=/home/dbwy/gcc-4.9.2/bin/g++ \
--with-cxx-optflags="-std=c++11 -O3 -mavx -march=native" \
--with-cxxgen-optflags="-std=c++11 -O3 -mavx -march=native"

**Comment by evaleev** [comment]
which version of autoconf in in PATH?

**Comment by wavefunction91** [comment]
autoconf 2.63

**Comment by evaleev** [comment]
OK, that's the problem. --config option to config.status was introduced in autoconf 2.68 . How big of a problem to upgrade? I can workaround instead, but it would be simpler to assume that autoconf is less than 5 years old (i.e. 2.68 or higher).

**Comment by wavefunction91** [comment]
Not a problem at all, that's kind of what I figured, I just wanted some input to see that there wasn't a more sinister problem. Thanks!
