### ISSUE TITLE
Hartree-Fock++ convergence issues.

### ISSUE THREAD

**Issue by calewis** [evaleev/libint#42]
hartreefock++ has developed convergence issues the last know working commit was c1be4f680ada1797e71741fa882b68e926fc05a9, but it is likely that the change is actually much much farther along. 

For example the following file has a very hard time converging in an aug-cc-pvdz basis. 
```
15

O       99.814000000   100.835000000   101.232000000
H       99.329200000    99.976800000   101.063000000
H       99.151600000   101.561000000   101.414000000
O       98.804000000    98.512200000    97.758100000
H       99.782100000    98.646900000    97.916700000
H       98.421800000    99.326500000    97.321300000
O       98.070300000    98.516900000   100.438000000
H       97.172800000    98.878600000   100.690000000
H       98.194000000    98.592200000    99.448100000
O      102.360000000   101.551000000    99.964500000
H      102.675000000   102.370000000   100.444000000
H      101.556000000   101.180000000   100.430000000
O      101.665000000    98.316100000    98.319400000
H      101.904000000    99.233800000    98.002000000
H      102.224000000    97.640900000    97.837700000
```

The current code converges to  
Hartree-Fock energy = -380.204496584440 after 79 iterations, but in the process goes as low as -407.002840370861 and as high as -350.927524169782

The old code converges to 
Hartree-Fock energy = -380.204496984182 after 16 iterations. 

The issue seems to be related to the 2 electron integrals but it is hard to be sure without further testing.

**Comment by evaleev** [comment]
Seems the current version computes fewer 2-body ints than needed. Investigating... 54fb92968796d8d0ac8b78cc9f88c2aef4043701 (Jul 4) is OK
