### ISSUE TITLE
Nan returned from compute when using cc-pv5z-ri

### ISSUE THREAD

**Issue by calewis** [evaleev/libint#43]
The engine is the two body two center engine.  

The call looks like 
``` c++
auto unit = Shell::unit();
auto ptr = eng.compute(s0, unit, s1, unit);
```

The shells are 
s0 =
Shell:( O={-1.3269582278103,-0.105938530313005,0.0187881522386705}
   {l=0,sph=0}
  488.561 74.062640090216

s1 =
Shell:( O={-1.3269582278103,-0.105938530313005,0.0187881522386705}
   {l=6,sph=1}
  3.26123 37.6580802979677

The values pointed two by the returned pointer are. 
nan nan nan nan 0 0 1.38777878078145e-17 3.42113882891801e-49 nan nan nan nan nan

**Comment by evaleev** [comment]
How did you configure libint compiler?

**Comment by calewis** [comment]
The one that fails with TCC (not sure which commit) was configured with 
```
#!/bin/sh

$HOME/software/libint/configure \
    --enable-eri=0 \
    --with-max-am=7 \
    --with-opt-am=4 \
    --disable-unrolling \
    --enable-generic-code \
    --enable-contracted-ints \
    --with-incdirs=-I/usr/local/include/eigen3 \
    --with-cxx-optflags="-std=c++11 -O3 -mavx -march=native" \
    --with-cxxgen-optflags="-std=c++11 -O3 -mavx -march=native" \
```

The one that fails with hf++ was commit cc6305f63c90ad841755f6612344408c0ca4e2d9 and was configured with 

```
$HOME/software/libint/configure \
    --enable-eri=0 \
    --with-max-am=7 \
    --with-opt-am=4 \
    --disable-unrolling \
    --enable-generic-code \
    --enable-contracted-ints \
    --with-incdirs=-I/usr/local/include/eigen3 \
    --with-cxx-optflags="-std=c++11 -O3 -DNDEBUG -mavx -march=native" \
    --with-cxxgen-optflags="-std=c++11 -O3 -DNDEBUG -mavx -march=native" \
```
