### ISSUE TITLE
thread scaling regression in recent hf++

### ISSUE THREAD

**Issue by evaleev** [evaleev/libint#44]
reported by @calewis

**Comment by evaleev** [comment]
@calewis I see a x8 speedup for pentacene on hyades (Intel2015, gcc4.8.3 stdlibc++), head node (LIBINT_NUM_THREADS=12). Can you get me more info on the setup where you observed the performance regression? Specifically compiler/C++ library.

**Comment by calewis** [comment]
@evaleev I will compare on New River please tell me which molecule and
basis set were used.

**Comment by calewis** [comment]
## Using gcc with -O3 -DNDEBUG -fopenmp -march=native.  The following is computed by skipping with thread_id and s1
My K timings on NewRiver for 10 waters in cc-pvdz 

Threads | timing | speedup
------------|---------|-------------
1 | 12.218 | 1
4 | 3.51 | 3.48
8 | 2.40 | 5.09
12| 1.79 | 6.83
24| 2.18 | 5.61

My K timings for 20 waters in cc-pvdz

Threads | timing | speedup
------------|---------|-------------
1 | 90.43 | 1
4 | 26.95 | 3.35
8 | 17.855 | 5.06
12| 18.82 | 4.80

## Switching back to  thread_id and s1234 in the s4 loop
10 waters in cc-pvdz 

Threads | timing | speedup
------------|---------|-------------
1 | 12.403 | 1
4 | 4.00 | 3.1
8 | 2.18 | 5.69
12| 2.25 | 5.51
24| 2.84  | 4.37

20 waters in cc-pvdz

Threads | timing | speedup
------------|---------|-------------
1 | 92.30 | 1
4 | 29.21 | 3.16
8 | 18.87 | 4.89
12| 20.65 | 4.47

**Comment by calewis** [comment]
## Using icpc with -O3 -DNDEBUG -openmp -xHost.  The following is computed by skipping with thread_id and s1234
K timings on NewRiver for 10 waters in cc-pvdz 

Threads | timing | speedup
------------|---------|-------------
1 | 11.92 | 1
2 | 6.28 | 1.90
4 | 3.49 | 3.41
8 | 1.96 | 6.08
12| 1.46 | 8.16
24| 1.16 | 10.28

K timings for 20 waters in cc-pvdz

Threads | timing | speedup
------------|---------|-------------
1 | 87.59 | 1
4 | 25.97 | 3.37
8 | 15.80  | 5.54
12 | 12.7473  | 6.88
24 | 11.93 | 7.34

## Using icpc with -O3 -DNDEBUG -openmp -xHost.  The following is computed by skipping with thread_id and s1

K timings on NewRiver for 10 waters in cc-pvdz 

Threads | timing | speedup
------------|---------|-------------
1 | 11.77 | 1
2 | 6.28 | 1.87
4 | 3.26 | 3.61
8 | 2.13 | 5.53
12| 1.57 | 7.50
24| 1.10 | 10.7

K timings for 20 waters in cc-pvdz

Threads | timing | speedup
------------|---------|-------------
1 | | 1
4 | 24.14  | 
8 | 14.99 |
12 |  | 
24 |  |

I will finish this last table later. Clearly icpc is better but not amazing.

**Comment by evaleev** [comment]
Try round robin allocation using s1s2 as the work unit

**Comment by calewis** [comment]
# K time for 10 waters using icpc and s12 to distribute work. 

Threads | timing | speedup
------------|---------|-------------
1 | 11.559 | 1
4 | 3.124 | 3.70 
8 | 1.746 | 6.62
12| 1.306 | 8.85 
24|  1.549 | 7.462

# K time for 20 waters using icpc and s12. 
Threads | timing | speedup
------------|---------|-------------
1 | 84.162 | 1
4 | 23.791 | 3.54
8 | 12.535 | 6.71
12| 9.486 | 8.87
24|  7.823 | 11.28

maybe a little better than before.
