### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mcbennet** [evaleev/libint#55]
I have had an error when compiling the latest libint source. I am using the intel compilers (I should mention that I see this error when using gnu compilers as well) on NERSC's Cori machine. I see the following output

I am attempting to compile libint's latest code from github on a Nersc machine. I am using the intel compilers (I also have tried the gnu compilers and I see the same failure that follows). I see the following output

**
....
generating code for OSVRRP1InBra_aB_l__0__p__1___TwoPRep_s__0__s__1___Ab__up_0 target=< l(0) p(1) | TwoPRep | s(0) s(1) > ^ { {6} }
generating code for OSVRRP0InBra_aB_l__0__s__1___TwoPRep_s__0__s__1___Ab__up_0 target=< l(0) s(1) | TwoPRep | s(0) s(1) > ^ { {6} }
Compilation finished. Goodbye.
echo "Last time library source was generated:\c" > source
date >> source
cd src; make TO_TOPDIR=../../.. TOPDIR=/global/homes/m/mcbennet/local/src/libint-build/src/lib/libint/../../.. SRCDIR=/global/homes/m/mcbennet/local/src/libint-2.1.0/src/lib/libint
CXX _aB_G__0__D__1___TwoPRep_S__0__D__1___Ab__up_0.lo
make[4]: Entering directory `/global/u1/m/mcbennet/local/src/libint-build/src/lib/libint/tmp/libint'
icpc: error #10236: File not found:  'yes'
make[4]: *** [_aB_G__0__D__1___TwoPRep_S__0__D__1___Ab__up_0.lo] Error 1
make[4]: Leaving directory `/global/u1/m/mcbennet/local/src/libint-build/src/lib/libint/tmp/libint'
make[3]: *** [../../../lib/libint2.la] Error 2
make[3]: Leaving directory `/global/u1/m/mcbennet/local/src/libint-build/src/lib/libint'
make[2]: *** [default] Error 1
make[2]: Leaving directory `/global/u1/m/mcbennet/local/src/libint-build/src/lib'
make[1]: *** [default] Error 1
make[1]: Leaving directory `/global/u1/m/mcbennet/local/src/libint-build/src'
make: *** [default] Error 1

**

I have attached the config.log file (under filename config_log.txt) and also my workflow was as follows

> module load boost
> module load gmp
> module load eigen3
> module load autoconf/2.69
> git clone https://github.com/evaleev/libint.git
> cd libint
> ./autogen.sh
> mkdir ../libint-build
> cd ../libint-build
> ./libint/configure ...
> make

[config_log.txt](https://github.com/evaleev/libint/files/190672/config_log.txt)

**Comment by evaleev** [comment]
please edit lib/MakeSuffixRules in the source dir and edit out the leading '@' on lines 8 and 16, then do 'make' in the build directory (no need to reconfigure or anything else), please report the output. The compilation command is somehow malformed.

**Comment by mcbennet** [comment]
Here is the output from 'make' after removing those two lines from the MakeSuffixRules files.

[make_output.txt](https://github.com/evaleev/libint/files/190700/make_output.txt)

**Comment by evaleev** [comment]
sorry, correction: lines 8 and **12** in lib/MakeSuffixRules

**Comment by mcbennet** [comment]
The output from 'make' is attached with the corrected lib/MakeSuffixRules file

[make_output.txt](https://github.com/evaleev/libint/files/190707/make_output.txt)

**Comment by evaleev** [comment]
It appears that the compilation went through ... strange, that should not have happened, did you just edit out the leading '@' or did you delete the lines?

**Comment by mcbennet** [comment]
Ah yes, apologies here is the corrected output with just '@' removed from the appropriate lines
[make_output.txt](https://github.com/evaleev/libint/files/190723/make_output.txt)

**Comment by evaleev** [comment]
The problem is that there is no value provided with --with-cxxgen-flags. It should be something like --with-cxxgen-flags='-O3 -march=native' .
