### ISSUE TITLE
assigning to 'value_type' (aka 'const double *') from incompatible type 'libint2::simd::VectorAVXDouble *'

### ISSUE THREAD

**Issue by vonDonnerstein** [evaleev/libint#64]
I have never had problems using this great library, until recently I wanted to compile it with AVX support. Whenever I specify `--with-real-type=libint2::simd::VectorAVXDouble` in the configuration of the actual compilation (no matter if I specified it for the generation of the compiler too), I end up with an engine.h and engine.impl.h which error in the compilation of my actual program, which may be as simple as:
```cpp
include <libint2.hpp>
int main() {
  return 0;
}
```

I am also specifying `-mavx` to my compiler in all compilation steps and have tried intel, gnu, and clang compiler. The latter gives the most elaborate error description: There appear more than 20 errors all related to conversions from `VectorAVXDouble` to `double`. E.g. 
```
libint2_binaries/include/libint2/engine.h:673:37: error: const_cast from 'libint2::simd::VectorAVXDouble **' to 'const real_t **' (aka 'const double **') is not allowed
    set_targets_ = (&targets_[0] != const_cast<const real_t**>(primdata_[0].targets));
```

Any idea what I might be doing wrong? Am I missing any further flags that have to be specified for consistency?

Any help and/or ideas are very much appreciated!

**Comment by evaleev** [comment]
There is no support for vectorization in the C++11 interface (only the Boys function engine is vectorized since this is easy to do without breaking the one-shell-at-a-time interface). This feature is in progress, subject to pending DOE funding. Meanwhile will make sure this error is communicated better.

p.s. thanks for using libint!

**Comment by vonDonnerstein** [comment]
Thank you for your quick reply. So I'll just wait for the completion of that feature and stick with the scalar code until then. All the best for your funding!
