### ISSUE TITLE
Multiple definitions upon link

### ISSUE THREAD

**Issue by matteopcc** [evaleev/libint#66]
Hi! I found the following multiple definitions upon link:

engine.impl.h(line 95): default_params(const Operator& oper);
engine.impl.h(line 690): unsigned int Engine::nparams() const;
engine.impl.h(line 700): unsigned int Engine::nopers() const;
engine.impl.h(line 764): any Engine::make_core_eval_pack(Operator oper) const.

**Comment by evaleev** [comment]
please try the latest version and report. should be fixed now. thanx!

**Comment by evaleev** [comment]
bump: @matteopcc plz try the latest version and report. should be fixed now.

**Comment by wavefunction91** [comment]
This fixed the issue on my end
