### ISSUE TITLE
Smth like a bug in class libint2::Shell

### ISSUE THREAD

**Issue by aoleynichenko** [evaleev/libint#71]
Hello, Eduard!

I'm trying to develop my own Hartree-Fock code using Libint library, because self-made code for integration is rather slow (https://github.com/aoleynichenko/minichem). I've took the example "hartree-fock.cc" as a basis. If I understand correctly, we use field Shell::Contraction::pure to tell Libint that the shell should be treated as Cartesian or Spherical. So, if pure == true, shell is spherical, otherwise we should use the "false" value to treat it as cartesian.
STO-3G basis set consists only of s- and p-functions, so, no matter how you set the parameter "pure".

However, I've tried to modify function make_sto3g_basis(): I've used "true" flag instead of "false" one for the "pure" field (for H and O). I got a completely different result:

pure == true: Hartree-Fock energy =      -4.655570501064 (completely wrong)
pure == false: Hartree-Fock energy =     -79.945406605489

As a result, the behavior of my own code is also unpredictable.

Please, could you point me out, what can be wrong and how this strange result can be fixed? I would like to use Libint's modern C++ interface, as recommended in the Wiki. Thank you in advance!

Best regards,
Alexander Oleynichenko,
Moscow State University

**Comment by evaleev** [comment]
should be fixed now, спасибо за репорт

**Comment by aoleynichenko** [comment]
Thank you, now all works perfectly! Спасибо Вам за исправления!
