### ISSUE TITLE
boost dependency

### ISSUE THREAD

**Issue by ajaypanyala** [evaleev/libint#76]
I see the following configure error. I was assuming that the latest libint automatically downloads/includes the necessary boost functionality. Could you please confirm this. Thanks!

```
checking for Boost::shared_ptr... no
checking for std::shared_ptr... yes
checking for Boost::mpl::for_each... no
configure: error: Boost::mpl is required. Please use the latest Boost library from boost.org and/or most standard-compliant C++ compiler.

```

**Comment by evaleev** [comment]
Libint *compiler* requires Boost MPL etc., and requires boost installed by the user. Libint *library* comes with (patched) boost preprocessor library bundled. Use a pre-generated library from one of the releases to avoid having to install boost.
