### ISSUE TITLE
Configuring fails with GMP 5.1/6.1

### ISSUE THREAD

**Issue by TariniHardikar** [evaleev/libint#81]
Hi, 

I'm trying to configure the libint compiler, using all the default options. The configuration quits with the message:

`configure: error: cannot link against GMP C++ library. Please get the latest GMP with support for C++. It can be obtained at gmplib.org .`

I believe I have the latest GMP with support for C++. I have attached the configure log as a txt file, which shows a few more errors: <ac_nonexistent.h> not found, and with errors in conftest.cpp.

Thanks!
[configurelog.txt](https://github.com/evaleev/libint/files/1198275/configurelog.txt)

**Comment by jdwhitfield** [comment]
Looking at your log files, the lines above the error message read

> configure:6674: result: no\
> configure:6674: checking for gmpxx.h\
> configure:6674: result: no\

The problem is with your path variables.  The C++ complier is not finding the header file, wherever you've installed it.

**Comment by evaleev** [comment]
@TariniHardikar please report how `configure` was  invoked ... as @jdwhitfield indicated, gmpxx.h is missing from the paths queried by the preprocessor. FYI, the failing test invokes `clang++ -c  -O2  -std=c++11  conftest.cpp`, i.e. gmpxx.h needs to be in `/usr/include` or (on some systems) `/usr/local/include`

**Comment by TariniHardikar** [comment]
Hi,

Thank you, I reinstalled gmp and reset the location to usr/local/include, and seems to have fixed it. It configures!

However, when I run `make`, the program doesn't end and has been generating the same error in params.h regarding the type of LIBINT2_REALTYPE.

Any suggestions?

**Comment by evaleev** [comment]
Please attach config.log and the output of make command.

**Comment by TariniHardikar** [comment]
I have attached the log file as a txt, and the terminal output is the first part, followed by an endless loop of the warning.


![screen shot 2017-08-04 at 16 20 12](https://user-images.githubusercontent.com/9437433
/28985889-aa17705c-7932-11e7-9333-d6c5c5bff706.png)
![screen shot 2017-08-04 at 16 30 33](https://user-images.githubusercontent.com/9437433/28985888-aa15405c-7932-11e7-90d7-7337945fc6db.png)
[config copy.txt](https://github.com/evaleev/libint/files/1201561/config.copy.txt)

**Comment by evaleev** [comment]
warnings are fine. did `make check` do anything?

p.s. it appears that you are trying to compile libint compiler in the source directory. This is not supported (for several reasons ... this is actually common, e.g. the Linux kernel). I recommend that you create a separate build directory (ideally, not a subdirectory of the source directory) and compile (e.g. `configure`, `make`, etc.) from there.

p.p.s. unless you are really need to generate a custom library it is recommended to use one of the pre-generated libraries, e.g. https://github.com/evaleev/libint/releases/download/v2.4.0-beta.3/libint-2.4.0-beta.3.tgz . Just download, `configure` (this can be done in the source), `make`, `make check`, `make install`

**Comment by lqhenwunai** [comment]
Hi,

I have met the same problem. I configured the gmp6.1.2 by ./configure --prefix=/usr/local/include/gmp.

And configure the libint2.6 as  ../../libint-2.6/configure --with-cxx=g++ --with-cxx-optflags=-O2 --enable-1body=2 --enable-eri=2 --enable-eri2=2 --enable-eri3=2 --with-max-am=6 

with the same return error:
checking gmpxx.h usability... no
checking gmpxx.h presence... no
checking for gmpxx.h... no
configure: error: cannot link against GMP C++ library. Please get the latest GMP with support for C++. It can be obtained at gmplib.org 

How do I include the gmp path correctly?

Many thanks for your help.

**Comment by evaleev** [comment]
> Hi,
> 
> I have met the same problem. I configured the gmp6.1.2 by ./configure --prefix=/usr/local/include/gmp.

`--prefix` specifies the install prefix for libint, not where to look for things.

Try `CPPFLAGS=-I/usr/local/include/gmp LDFLAGS=-I/usr/local/lib ./configure ....`

**Comment by lqhenwunai** [comment]
Dear Prof. Valeev,
Many thanks for your reply.

I tried your suggestion but the same error persists. I have also tried ../../libint-2.6/configure --with-cxx=g++ --with-cxx-optflags=-O2 --enable-1body=2 --enable-eri=2 --enable-eri2=2 --enable-eri3=2 --with-max-am=6 --with-cxxflags='-I/usr/local/include/gmp/' but it does not help.

As a desperate attempt, I do have successfully compiled libint-2.0.3. But I am not sure how to call the functions. i.e. The manual says only libint2.h is required to be included. And the test_eri.cc writes something like:

  // static initialziation of the library (one needs to happen once per process)
  LIBINT2_PREFIXED_NAME(libint2_static_init)();

But when I included linint2.h and using namespace linint2, and call this initialization function, it returns with error with undefined reference to... (sorry I don't remember exactly the error message).

What did I miss?

Many thanks for your help.

**Comment by evaleev** [comment]
Look in `config.log` for the hints why GMP is not found. It might be that you do not specify the location of the GMP library, and/or the header file location is not correct. To start, please report the output of `find /usr/local -name "libgmp*"` and `find /usr/local -name gmpxx.h` ... I'm not sure if you have the correct locations.

P.S. Are you sure you want second derivative integrals for l=6? The amount of code this will generate will be enormous. And the use of second-derivative integrals with such high angular momenta is unlikely to be useful in practice. In ORCA we limit 4-c 2nd derivatives to l=4, higher angular momenta require density fitting (thus only 2- and 3-center integrals).

**Comment by evaleev** [comment]
@lqhenwunai to avoid polluting this issue (it has been resolved as far as I know) please create another.
