### ISSUE TITLE
Fail configuration if Eigen is not found.

### ISSUE THREAD

**Issue by ryanmrichard** [evaleev/libint#92]
Because the dependency on Eigen is entirely within header files that are part of the public API it is possible to compile libint without Eigen; however, it is not possible to use libint in another project without Eigen (at least through the C++11 API).  I'd be curious to hear @evaleev's take on the issue, but my opinion is that libint is responsible for ensuring that its dependencies are met.  If @evaleev agrees then it should suffice to 
crash the autoconf at line 1379, which is where it looks for Eigen (I think; I actually have never written an autoconf file...).

**Comment by evaleev** [comment]
@ryanmrichard C++ API is an optional component of libint ... some codes like ORCA do not use it, so this would break them. This check should be done on the consumer side. I can add a mechanism for header-only consumers to check that C++ API prerequisites is available.
