### ISSUE TITLE
Problem with variadic macros

### ISSUE THREAD

**Issue by gba** [evaleev/libint#97]
When compiling Libint 2.4.1 using GCC 6.3.0, on one Linux system I get the error message

 libint/build_libint.cc:38:4: error: #error "your compiler does not provide variadic macros (but does support C++11), something is seriously broken, please create an issue at https://github.com/evaleev/libint/issues"

whereas on another Linux computer the code builds fine with the same version of GCC.

**Comment by evaleev** [comment]
I suspect the version of Boost is too old in the platform where you see the error. Would you please check the version of boost in standard location (likely `/usr/include/boost/version.hpp`, unless your compiler looks in another location like `/usr/local`)

**Comment by gba** [comment]
The standard Boost version was 1.41. When using Boost version 1.60, the code compiles. 

Thanks for the help!
